parameters:
    env(DB_HOST): ''
    env(DB_PORT): ''
    env(DB_NAME): ''
    env(DB_USER): ''
    env(DB_PASS): ''

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%env(DB_HOST)%"
        port:     "%env(DB_PORT)%"
        dbname:   "%env(DB_NAME)%"
        user:     "%env(DB_USER)%"
        password: "%env(DB_PASS)%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
